// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getEnvironmentConfig } from '../../config/environment';

const { supabase: supabaseEnv } = getEnvironmentConfig();
const SUPABASE_URL = supabaseEnv.url;
const SUPABASE_PUBLISHABLE_KEY = supabaseEnv.anonKey;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
