// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxrkezxytovaxlpjnbda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4cmtlenh5dG92YXhscGpuYmRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NTczMzQsImV4cCI6MjA2MzQzMzMzNH0.JWzIz01JTcrqBvGixAjMP19jN36nNYZhRCWLWstuURE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);